name: Deploy Terraform

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ 'main', 'terratag-test' ]
jobs:
  Terraform:

    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TF_VAR_machine_type: e2-medium
      TF_VAR_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      TF_IN_AUTOMATION: true
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.2.1
        name: Setup Terraform
        with:
          terraform_version: 1.0.8
          terraform_wrapper: false
          # more setup-terraform configuration. See https://github.com/hashicorp/setup-terraform#usage

      - name: Terraform init
        id: init
        run: |
          terraform --version
          terraform init
          terraform validate

      - uses: env0/terratag-action@1.0.2
        name: Terratag
        with:
          tags: |
            {
              "environment_name":"github_terratag_blog_post"
            }
          dir: test/fixture/terraform_13_14/aws_autoscaling_group/input 

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=.tf-plan -destroy

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve .tf-plan
