name: Deploy Terraform

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ 'main', 'adding-terraform' ]
jobs:
  Terraform:

    runs-on: ubuntu-20.04
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TF_VAR_machine_type: e2-medium
      TF_VAR_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5
          # more setup-terraform configuration. See https://github.com/hashicorp/setup-terraform#usage
      - name: Node version
        run: node --version

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terratag by env0
        run:
          - curl -O -L https://github.com/env0/terratag/releases/download/v0.1.29/terratag_0.1.29_linux_amd64.tar.gz
          - tar -xvf terratag_0.1.29_linux_amd64.tar.gz
          - ./terratag -dir=${TF_ROOT} -tags='{"environment_name":"github_terratag_blog_post"}'

      - name: Terraform Plan
        id: plan
        run: terraform plan

      # - name: Terraform Apply
      #   id: apply
      #   run: terraform apply
